since: 2018
# icp 备案号
icp:
# 公安备案号
ga:

# 导航元素
nav:
  showArchives: false
  showTags: false
  showAbout: false
  showHome: false
  showLinks: false

footer:
  showLicense: true
  showLinks: true
  showIcp: false
  showGaIcp: false
  # 显示统计
  showBusuanziViewCount: false
  showRss: true
  showSitemap: true

post:
  showBusuanziViewCount: false

# 百度统计
baidu_analytics:
# google 统计
google_analytics:
busuanzi_enable: false
rss: /atom.xml
sitemap: /sitemap.xml
