__: snow-white

since: 2018
# icp 备案号
icp:
# 公安备案号
ga:

# 导航元素
nav:
  showArchives: false
  showTags: false
  showAbout: false
  showHome: false

post:
  showVisit: false

# 显示统计
view_count: false

# Baidu Analytics
baidu_analytics:
# Google Analytics
google_analytics: